service:
  enabled: true
  port: 80
  targetPort: 3000
  nodePort: 30100
  secrets: []
  serviceType: NodePort
  ingress:
    enabled: true
    paths:
      - /
  resources:
    requests:
      memory: 128Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 500m
