on:
  push:
    branches:
      - main
jobs:
  publish-docker-image:
    uses: third-place/actions/.github/workflows/publish-docker-image.yaml@main
    secrets: inherit
    with:
      name: third-place/web-ui
      directory: .
  deploy-service:
    needs: publish-docker-image
    uses: third-place/actions/.github/workflows/deploy-service.yaml@main
    secrets:
      PAT: ${{ secrets.CR_PAT }}
