on:
  push:
    tags:
      - '*'
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/setup-yarn@v1
      - run: yarn test
      - run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - run: docker build . --tag ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
  deploy-to-dev:
    uses: third-place/actions/.github/workflows/deploy-to-env.yaml@main
    with:
      tag: ${{ inputs.tag }}
      env: dev
    secrets: inherit
