on:
  push:
    branches:
      - main
jobs:
  publish-docker-image:
    uses: third-place/actions/.github/workflows/publish-docker-image.yaml@main
    secrets: inherit
    with:
      name: third-place/web-ui
      directory: .
      dockerfile: Dockerfile.dev
  deploy-service:
    needs: publish-docker-image
    uses: third-place/actions/.github/workflows/deploy-env.yaml@main
    with:
      service: web-ui
      env: dev
    secrets:
      PAT: ${{ secrets.CR_PAT }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DEV }}
