on:
  push:
    branches:
      - main
jobs:
  publish-docker-image:
    uses: third-place/actions/.github/workflows/publish-docker-image.yaml@main
    secrets: inherit
    with:
      name: web-ui
      directory: .
      dockerfile: Dockerfile.dev
  deploy-service:
    needs: publish-docker-image
    uses: third-place/actions/.github/workflows/deploy-env.yaml@main
    with:
      name: web-ui
      env: dev
    secrets: inherit
