apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/third-place/web-ui:v0.1.13
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: REACT_APP_BASE_URL
              value: https://api.thirdplaceapp.com
            - name: REACT_APP_IMAGE_BASE_URL
              value: https://third-place-prod.s3.us-west-2.amazonaws.com
            - name: REACT_APP_ENV
              value: dev
      imagePullSecrets:
        - name: dockerconfigjson-github-com
